[project]
name = "project"
version = "0.1.0"
description = ""
authors = [
    {name = "katp1998",email = "katp1998is@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
